server:
  port: 8080
spring:
  application:
    name: "AuditorMs"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  db:
    schema: "public"
    initial-size: 20
    max-size: 40
  kafka:
    consumer-group: "corex-recovery.consumer-group"
    topics:
      iseries-topic: "deposits.generalinformationupdatedv1"
      vault-topic: "vault.api.v1.postings.posting_instruction_batch.created"
      dlq-topic: "deposits.generalinformationupdatedv1.dlq"  #Pendiente
account:
  filter:
    excluded-status: "CANCELADO"
    excluded-savings-accounts: "60,61"
    excluded-checking-accounts: "18,24,41,42,43,44"
aws:
  region: "us-east-1"
  strimzi-secret-name: "nu6410005-recovery-dev-secret-recovery-scram-secret-operative-eda"
  vault-kafka-secret-name: "nu6410002-query-model-corex-dev-secret-vault-kafka"
  db-secret-name: "nu6410005-recovery-cxauddcd-dev-secretrds-admin"
logging:
  level:
    root: INFO
    co.com.bancolombia: DEBUG
    io.r2dbc.postgresql.QUERY: INFO